FILE( GLOB_RECURSE INCLUDES RELATIVE ${PROJECT_SOURCE_DIR} include/*.h )
FILE( GLOB_RECURSE LAUNCH RELATIVE ${PROJECT_SOURCE_DIR} launch/*.launch )
FILE( GLOB_RECURSE LAUNCH RELATIVE ${PROJECT_SOURCE_DIR} test/*.launch )
FILE( GLOB_RECURSE LAUNCH RELATIVE ${PROJECT_SOURCE_DIR} test/*.cpp )
FILE( GLOB_RECURSE LAUNCH RELATIVE ${PROJECT_SOURCE_DIR} scripts/*.* )

ADD_CUSTOM_TARGET(${PROJECT_NAME}_NonBuildingFiles SOURCES ${LAUNCH} ${INCLUDES} )
